# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in beyond_the_vale_of_madness.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.7"

gem "artii", "~> 2.1.2"

gem "crapshoot", ~> "0.5.1"

gem "colorize", ~> "0.8.1"

gem "tty-prompt", ~> "0.21.0"

gem "yaml", ~> "0.1.1"